### ISSUE TITLE
confirm only annotated podspecs are mutated

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/apm-k8s-attacher#21]
check that other annotated resources, eg. Services, do not appear in the webhook receiver on creation

**Comment by simitt** [comment]
I think this was supposed to be part of some testing efforts before GA.

**Comment by jackshirazi** [comment]
Created service (`java-interesting` was defined and working in the webhook against a pod with a Java app)
```
apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations:
    co.elastic.apm/attach: java-interesting
spec:
  selector:
    app.kubernetes.io/name: MyApp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9376
```

Output of describe
```
$ kubectl describe service/my-service
Name:              my-service
Namespace:         default
Labels:            <none>
Annotations:       co.elastic.apm/attach: java-interesting
Selector:          app.kubernetes.io/name=MyApp
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.106.158.130
IPs:               10.106.158.130
Port:              <unset>  80/TCP
TargetPort:        9376/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>
```

Nothing changed, so confirming that at least Service isn't changed and by inference other resources
